version: '3.8'


# mongodb replica setup
services:
  mongo:
    image: mongo:6
    container_name: mongo2
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./volumes/data/mongo-rep:/data/mongo/db
      - ./volumes/config/mongo-rep:/etc/mongo
      - ./volumes/config/mongo-rep/mongo-keyfile:/etc/mongo-keyfile
      - ./volumes/config/mongo-rep/init.js:/docker-entrypoint-initdb.d/init.js
    command:
      [
        'mongod',
        '--replSet',
        'rs0',
        '--bind_ip_all',
        '--keyFile',
        '/etc/mongo-keyfile',
      ]
    networks:
      - app-network

  mongo-init:
    image: mongo:6
    container_name: mongo-init
    depends_on:
      - mongo
    networks:
      - app-network
    command: >
      bash -c "
      sleep 5 &&
      mongosh --host mongo2 --username user --password pass --authenticationDatabase admin --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [
            { _id: 0, host: \"mongo2:27017\" }
          ]
        });
      '
      "

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongo2:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo-init
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
