version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.8.4
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G

  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "8091:8091"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CFG_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_JMX_PORT: 9101
      KAFKA_CFG_JMX_HOSTNAME: localhost
      ALLOW_PLAINTEXT_LISTENER: yes
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 2G

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
  
  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8082:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - app-network

  conduktor:
    image: conduktor/conduktor-platform:1.25.1
    container_name: conduktor
    depends_on:
      - kafka
    ports:
      - '8095:8080'
    environment:
      CONDUKTOR_PLATFORM_KAFKA: 'PLAINTEXT://kafka:9092'
      CDK_DATABASE_URL: 'postgresql://dk_user:pg_pass@postgres:5432/postgres'
      CDK_ADMIN_EMAIL: "admin@me.io"
      CDK_ADMIN_PASSWORD: "admin"
      CONDUKTOR_PLATFORM_SCHEMA_REGISTRY: 'http://schema-registry:8081'
      # CDK_DATABASE_NAME: 'postgres'
      # CDK_DATABASE_USER: 'dk_user'
      # CDK_DATABASE_PASSWORD: 'pg_pass'

    networks:
      - app-network

  postgres:
    image: postgres:16.8
    container_name: postgres
    environment:
      POSTGRES_USER: dk_user
      POSTGRES_PASSWORD: pg_pass
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
