# curl --location 'http://localhost:3055/internal/ranking/rank'
#--header 'Content-Type: application/json'
#--data '{
#    "userId": "66ab4a056995cd5ed6b7bc75",
#    "offers": [
#        {
#            "id": "test-game-1"
#        }
#    ]
#}'
POST http://localhost:3055/internal/ranking/rank
Content-Type: application/json

{
    "userId": "66ab4a056995cd5ed6b7bc75",
    "offers": [
        {
            "id": "test-game-1"
        }
    ]
}

###

